# Generated by Django 6.0.2 on 2026-03-10 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('alumnos', models.ManyToManyField(blank=True, related_name='cursos', to='alumnos.alumno')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='profesores.profesor')),
            ],
        ),
    ]
